name: arxiv_recsys  
channels:
  - defaults
dependencies:
  - python=3.8  # Replace with your preferred Python version
  - tkinter=8.6  # Replace with your tkinter version
  - pandas=1.3.3
  - scikit-learn=0.24.2
  - tqdm=4.62.2
  - requests=2.26.0
  - feedparser=6.0.2
